---
title: "Today's Top Hits"
format: 
    dashboard: 
        logo: "images/logo.png"
        orientation: columns
---

## Column {width="35%"}

Placeholder text for Column 1

```{r, load-packages}
#| echo: false
#| include: false

library(tidyverse)
library(httr2)
```



```{r, create-access-token}
#| echo: false
#| include: false
#| 
# Define client ID and client secret to facilitate Spotify access
client_id <- Sys.getenv("SPOTIFY_CLIENT_ID")
client_secret <- Sys.getenv("SPOTIFY_CLIENT_SECRET")

req_access_token <- request("https://accounts.spotify.com/api/token") |> 
  req_method("POST") |> 
  req_body_raw(paste0("grant_type=client_credentials&client_id=", 
                      client_id, 
                      "&client_secret=",
                      client_secret
                      ), "application/x-www-form-urlencoded") |> 
  req_perform() |> 
resp_body_json()

spotify_access_token <- req_access_token$access_token
```


```{r, playlist_id}

#| echo: false


tth <- request("https://api.spotify.com/v1/playlists/37i9dQZF1DXcBWIGoYBM5M") |> 
  req_method("GET") |> 
  req_headers(
    Authorization = paste0("Bearer ", spotify_access_token),
    ) |>
  req_perform() |> 
  resp_body_json()

#Extract track names and artists by calling specific elements

tth$tracks$items[[1]]$track$name

tth$tracks$items[[1]]$track$artists

#Create data frame with top hits information
top_hits_df <- data.frame(
    song_name = unlist(lapply(tth$tracks$items, FUN = function(x) {x$track$name})),#unlist to get a vector
    song_id = unlist(lapply(tth$tracks$items, FUN = function(x) {x$track$id})),
    artist_name = unlist(lapply(tth$tracks$items, FUN = function(item) {item$track$album$artists[[1]]$name})),
    album_art = unlist(lapply(tth$tracks$items, FUN = function(item) {item$track$album$images[[1]]$url})),
    track_duration = unlist(lapply(tth$tracks$items, FUN = function(item) {item$track$duration_ms})),
    popularity = unlist(lapply(tth$tracks$items, FUN = function(item) {item$track$popularity}))
)

head(top_hits_df)

```

## Column {width="65%"}

### Row {height="10%"}

```{r}
paste0("My username is: ", Sys.getenv("MY_USERNAME"))
```

Placeholder text for Column 2, Row 1

### Row {height="70%"}

Embeds a how-to video with iframe!

<iframe width="560" height="315" src="https://www.youtube.com/embed/y7ZdBUtQxqg?si=J3Lw7At33lhB7lVy" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

Placeholder text for Column 2, Row 2

### Row {height="20%"}

Rest in Power, Francoise Hardy (1944-2024)

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/6g5qyQrAcoBX4X7XjxBoTO?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

Placeholder text for Column 2, Row 3
